#server:
#  port: 8002
spring:
  application:
    name: prod
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'